# Generated by Django 5.0.6 on 2024-05-27 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagrams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.ImageField(upload_to='lines/', verbose_name='lineas')),
                ('hex_name', models.CharField(max_length=150, verbose_name='hexagrama')),
            ],
        ),
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paintings/', verbose_name='Imagen')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ArtEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay', models.CharField(max_length=8000, verbose_name='ensayo')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.paintings', verbose_name='Pintura')),
            ],
        ),
    ]
