# Generated by Django 5.0.6 on 2024-05-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artessay',
            options={'verbose_name': 'Ensayo', 'verbose_name_plural': 'Ensayos'},
        ),
        migrations.AlterModelOptions(
            name='hexagrams',
            options={'verbose_name': 'Hexagrama', 'verbose_name_plural': 'Hexagramas'},
        ),
        migrations.AlterModelOptions(
            name='paintings',
            options={'verbose_name': 'Pintura', 'verbose_name_plural': 'Pinturas'},
        ),
    ]
