# Generated by Django 5.0.6 on 2024-05-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_artessay_options_alter_hexagrams_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artessay',
            name='main_hex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='main_hex', to='store.hexagrams', verbose_name='Hexagrama principal'),
        ),
        migrations.AddField(
            model_name='artessay',
            name='sec_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_hex', to='store.hexagrams', verbose_name='Hexagrama secundario'),
        ),
    ]
